export const ACTION = {
  SET_PROJECTS: "SET_PROJECTS",
  SET_CURRENT_PROJECT: "SET_CURRENT_PROJECT",
  SET_SCENARIOS: "SET_SCENARIOS",
  PUSH_DOCUMENT: "PUSH_DOCUMENT",
  SET_CURRENT_DOCUMENT: "SET_CURRENT_DOCUMENT",
  POP_DOCUMENT: "POP_DOCUMENT",
  SET_RESPONSE: "SET_RESPONSE",
  SET_UNSAVED_CHANGE: "SET_UNSAVED_CHANGE"
}