export const ACTION = {
  SET_PROJECTS: "SET_PROJECTS",
  SET_CURRENT_PROJECT: "SET_CURRENT_PROJECT",
  SET_SCENARIOS: "SET_SCENARIOS",
  SET_REQUESTS: "SET_REQUESTS",
  PUSH_DOCUMENT: "PUSH_DOCUMENT",
  SET_CURRENT_DOCUMENT: "SET_CURRENT_DOCUMENT",
  POP_DOCUMENT: "POP_DOCUMENT",
  SET_RESPONSE: "SET_RESPONSE",
  UPDATE_UNSAVED_CHANGE: "UPDATE_UNSAVED_CHANGE",
  SET_UNSAVED_CHANGE: "SET_UNSAVED_CHANGE",
  UPDATE_OPEN_DOCUMENTS: "UPDATE_OPEN_DOCUMENTS",
  SET_OPENDDOC: "SET_OPENDDOC",

}